/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GlassDiv {
    }
    interface ProfileCard1 {
        "name": string;
    }
}
declare global {
    interface HTMLGlassDivElement extends Components.GlassDiv, HTMLStencilElement {
    }
    var HTMLGlassDivElement: {
        prototype: HTMLGlassDivElement;
        new (): HTMLGlassDivElement;
    };
    interface HTMLProfileCard1Element extends Components.ProfileCard1, HTMLStencilElement {
    }
    var HTMLProfileCard1Element: {
        prototype: HTMLProfileCard1Element;
        new (): HTMLProfileCard1Element;
    };
    interface HTMLElementTagNameMap {
        "glass-div": HTMLGlassDivElement;
        "profile-card-1": HTMLProfileCard1Element;
    }
}
declare namespace LocalJSX {
    interface GlassDiv {
    }
    interface ProfileCard1 {
        "name"?: string;
    }
    interface IntrinsicElements {
        "glass-div": GlassDiv;
        "profile-card-1": ProfileCard1;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "glass-div": LocalJSX.GlassDiv & JSXBase.HTMLAttributes<HTMLGlassDivElement>;
            "profile-card-1": LocalJSX.ProfileCard1 & JSXBase.HTMLAttributes<HTMLProfileCard1Element>;
        }
    }
}
